[package]
name = "chord3"
version = "0.3.1-PRE"
authors = ["Rasmus Kaj <kaj@kth.se>"]
repository = "https://github.com/kaj/chord3"
description = "Create pdf songbooks from chopro source."
license = "Beerware"

[dependencies]
clap = "^2"
lazy_static = "^1.0.0"
pdf-canvas = "^0.6"
regex = "^1.0.1"
